name: Deploy to Astronomer Cloud

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust according to your Astro project requirements

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash
          astro version

      - name: Authenticate to Astronomer Cloud
        env:
          ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
          ASTRONOMER_SECRET: ${{ secrets.ASTRONOMER_SECRET }}
        run: |
          astro login --token-login "$ASTRONOMER_SECRET"

      - name: Deploy to Astronomer Cloud
        run: |
          astro deploy ${{ secrets.ASTRO_DEPLOYMENT_ID }} --dags
